---
language: python
python:
  - "3.4"
  - "3.5"

matrix:
  allow_failures:
    - python: "3.4"


cache:
  pip: true
  directories:
    - eggs/

before_install:
  - sudo apt-get update -qq && sudo apt-get install -y libpulse0

install:
  - python3 bootstrap.py
  - bin/buildout

script: bin/test
