---
language: python
python:
  - '3.4'
  - '3.5'

matrix:
  allow_failures:
  - python: '3.4'

cache:
  pip: true
  directories:
  - eggs/

before_install:
- sudo apt-get update -qq && sudo apt-get install -y libpulse0

install:
- python3 bootstrap.py
- bin/buildout

script: bin/test

deploy:
  provider: pypi
  user: naftulikay
  password:
    secure: JBpkpdXGXD37kvmwQxSSzUBnev0rNtg5OyQxX7yQlBDTpJzlzAu5LDmw0mGJnf+XflxALmf9PzL877YQT5OZ9ap38g9ESD0ujfQwEp38OAVgHpk7MEncXroDLrQlKu1H8A6m7Qw+Nm/6AX1z5FqeW8LSW4eLRhmJAJ9R7gaHhJ4FtMrqnMrWg9tcgUTMEns/gPNoMCeUtTWDL8dH+9FiFKd9UpLS9xQn4LNVo6XjUpNnux5+Pv2m4sXHo7d5Kju0OxcSkMZniiWxWTBXc/P91vH68GeIkW7OMjlrcLkJu/GtcCCROB9PAGVNyPv5XSa2KdshFdQpXLlBZv2TQDNTieH48fiELHH14bGwHkCW9T5d9vOE6tAxb6OlXgNv1eXBHVg2LXCys8P4/vJwJevwo0pysmFKJYB2QZJ3iOh6/cp152fhjTglupnL4hUKU6K6ZHYPfmCixvI0F+h/6L18ZK76U4WgC/FcQGFGKEHvDcxl80K2b+qk0h9pjsVog/13rRIWyxk+jpEBI0Qp5jS7WyCvqXOW2nhLOchYgiIwEzBr5fjrK9NnObJzAyR623dE0Q/OkTqEgORURiGKUw+2UCEp3602SGteZGG0n2O+XjXLei9tUidIeCKXkAZjwDrkPX9lO7q6YTfhJs9DCuacHOMhtdWUNyqzgnaJl7TJr9s=
  on:
    branch: master
